version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - line: %(lineno)d - %(levelname)s - %(message)s'
  file:
    format: '%(asctime)s - %(name)s - function: %(funcName)s - line: %(lineno)d - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: file
    filename: logs.log
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no
  fileLogger:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: DEBUG
  handlers: [console]