version: 1
formatters:
  console:
    format: "Time:%(asctime)s, <Level-%(levelname)s>, \n [logger Name: %(name)s ], Line: %(lineno)d == %(message)s"
  file:
    format: 'Time:%(asctime)s, <Level-%(levelname)s>, {function: %(funcName)s} [Name: %(name)s], Line: %(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: file
    filename: logs.log
loggers:
  console_logger:
    level: INFO
    handlers: [console]
    propagate: no
  file_logger:
    level: INFO
    handlers: [file]
    propagate: no
root:
    level: INFO
    handlers: [console]